routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('home');
Route::post('/sendMail', 'EmailController@sendEmail')->name('sendMail');

Auth::routes(['register' => false]);

Route::get('/dashboard', function() {
    return view('admin/index');
})->name('dashboard')->middleware('auth');

Route::namespace('Admin')->group(function () {
    Route::resource('packages', 'PackageController');
    Route::resource('sliders', 'SliderController');
    Route::resource('web_setting', 'WebSettingController')->only([
        'index', 'store'
    ]);
    Route::resource('forms', 'FormsController')->only([
        'index', 'store', 'show', 'destroy'
    ]);
});
Route::get('/pendaftaran_alert', function() {
    return view('partials/formAlert');
});

Route::get('/contact_alert', function() {
    return view('partials/contactAlert');
});

resources/views/partials/contactAlert.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indihome</title>
    <link rel="stylesheet" href="{{asset('assets/vendors/bootstrap/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/vendors/mdi/css/materialdesignicons.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
</head>
<body> -->
    @extends('layouts/frondendTemplate')
    @section('content')
    <div class="container clearfix mt-5 pt-5 mb-5">
        <div class="row justify-content-center mt-4">
            <div class="col-lg-5">
                <div class="card">
                    <div class="card-body text-center">
                        <h5>Terimakasih</h5>
                        <p>Pesan kamu berhasil terkirim sebagai email di perangkat kami.</p>
                        <a href="{{ route('home') }}"><button class="btn btn-danger">Kembali ke beranda</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection
    <!-- <script type="text/javascript" src="{{asset('/assets/vendors/jquery/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/vendors/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/main.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/alert.js')}}"></script> -->
</body>
</html>

resources/views/partials/flash_message.blade.php
@if(Session::has('flash_message'))
    <div class="alert alert-dismissible fade show {{ Session::has('penting') ? 'alert-danger alert-important' : 'alert-success' }}" role="alert">
        {{ Session::get('flash_message') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/partials/footer.blade.php
	<div class="modal fade" id="modalUploadDocument" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header border-bottom-0">
					<h5 class="modal-title" id="exampleModalLongTitle">Choose document workflow</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body mx-1 mb-2">
					<div class="row">
						<div class="col">
							<a href="{{asset('/upload')}}" class="text-dark">
								<div class="card text-center">
									<i class="mdi mdi-fingerprint mdi-48px"></i>
									<h6>Sign & Share</h6>
								</div>
							</a>
						</div>
						<div class="col">
							<a href="{{asset('/upload')}}" class="text-dark">
								<div class="card text-center">
									<i class="mdi mdi-account-group mdi-48px"></i>
									<h6>Share Only</h6>
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript" src="{{asset('/assets/vendors/jquery/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/vendors/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/main.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/alert.js')}}"></script>
	<script>
		$(document).ready(function() {
            $('#ModalDelete').on('show.bs.modal', function(e) {
                var id = $(e.relatedTarget).data('id');
                $(this).find('.modal-body #id').val(id);
            });
        })
	</script>

resources/views/partials/formAlert.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Indihome</title>
    <link rel="stylesheet" href="{{asset('assets/vendors/bootstrap/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/vendors/mdi/css/materialdesignicons.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
</head>
<body> -->
    @extends('layouts/frondendTemplate')
    @section('content')
    <div class="container clearfix mt-5 pt-5 mb-5">
        <div class="row justify-content-center mt-4">
            <div class="col-lg-5">
                <div class="card">
                    <div class="card-body text-center">
                        <h5>Terimakasih</h5>
                        <p>Permintaan kamu sedang kami proses. Pastikan selalu hp kamu aktif agar dapat tim kami hubungi</p>
                        <a href="{{ route('home') }}"><button class="btn btn-danger">Kembali ke beranda</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection
    <!-- <script type="text/javascript" src="{{asset('/assets/vendors/jquery/jquery.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/vendors/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/main.js')}}"></script>
	<script type="text/javascript" src="{{asset('/assets/js/alert.js')}}"></script> -->
</body>
</html>

resources/views/partials/header.blade.php
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Super Indihome</title>
	<link rel="stylesheet" href="{{asset('assets/vendors/bootstrap/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/vendors/mdi/css/materialdesignicons.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">

resources/views/partials/modalDelete.blade.php
<div class="modal fade" id="ModalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body" style="padding-top:1em !important; padding-bottom:0.5em !important;">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="mb-3">
                    Apa anda yakin ingin menghapusnya ?
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row justify-content-md-center">
                <div>
                  {!! Form::open(['method' => 'DELETE', 'route' => [$route, 'delete']]) !!}
                      {!! Form::text('id', null, ['id' => 'id', 'hidden']) !!}
                      <button type="submit" class="btn btn-sm btn-outline-danger">Yes</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Cencel</button>
                  {!! Form::close() !!}
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/partials/navbar.blade.php
    <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom">
        <div class="form-inline">
            <i class="mdi mdi-menu mdi-24px d-block d-lg-none pointer text-dark mr-2" id="menu"></i>
            <a class="navbar-brand" href="/dashboard">Prakerja</a>
        </div>
        <div class="dropdown ml-auto">
            <a href="#" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="mdi mdi-account-circle-outline text-dark mdi-24px"></i>
            </a>
            <div class="dropdown-menu rounded" aria-labelledby="dropdownMenu">
                <a class="dropdown-item" href="/profil">
                    <i class="mdi mdi-18px mdi-account-circle-outline"></i><span>Profil</span>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item text-danger" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="mdi mdi-18px mdi-login-variant"></i><span>{{ __('Logout') }}</span>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </a>
            </div>
        </div>
    </nav>

resources/views/partials/sidebar.blade.php
	<div class="sidebar">
		<a href="{{ route('dashboard') }}" class="{{($halaman == 'dashboard') ? 'active' : ''}}">
			<i class="mdi mdi-apps mdi-18px"></i><span>Dashboard</span>
		</a>
		<a href="{{ route('web_setting.index') }}" class="{{($halaman == 'web_setting') ? 'active' : ''}}">
			<i class="mdi mdi-map-marker-outline mdi-18px"></i><span>Web Setting</span>
		</a>

		<a href="{{ route('sliders.index') }}" class="{{($halaman == 'sliders') ? 'active' : ''}}">
			<i class="mdi mdi-map-marker-outline mdi-18px"></i><span>Slider</span>
		</a>

		<a href="{{ route('packages.index') }}" class="{{($halaman == 'packages') ? 'active' : ''}}">
			<i class="mdi mdi-map-marker-outline mdi-18px"></i><span>Package</span>
		</a>

		<a href="{{ route('forms.index') }}" class="{{($halaman == 'forms') ? 'active' : ''}}">
			<i class="mdi mdi-map-marker-outline mdi-18px"></i><span>Formulir</span>
		</a>
	</div>
	<div class="overlay"></div>