routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('home');
Route::post('/sendMail', 'EmailController@sendEmail')->name('sendMail');

Auth::routes(['register' => false]);

Route::get('/dashboard', function() {
    return view('admin/index');
})->name('dashboard')->middleware('auth');

Route::namespace('Admin')->group(function () {
    Route::resource('packages', 'PackageController');
    Route::resource('sliders', 'SliderController');
    Route::resource('web_setting', 'WebSettingController')->only([
        'index', 'store'
    ]);
    Route::resource('forms', 'FormsController')->only([
        'index', 'store', 'show', 'destroy'
    ]);
});
Route::get('/pendaftaran_alert', function() {
    return view('partials/formAlert');
});

Route::get('/contact_alert', function() {
    return view('partials/contactAlert');
});

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'sliders';

    protected $fillable = [
        'image', 'title', 'order'
    ];

    public $timestamps = false;
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Slider;
use App\Http\Requests\Admin\SliderRequest;
use App\Services\Slider\SliderServices;
use Session;

class SliderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => 
            ['show']
        ]);
    }

    public function index()
    {
        $data_slider = SliderServices::getAll();
        return view('admin/slider/index', compact('data_slider'));
    }


    public function create()
    {
        return view('admin/slider/create');
    }

    public function store(SliderRequest $request)
    {
        SliderServices::create($request);
        Session::flash('flash_message', 'Data Slider Berhasil di Tambahkan');
        return redirect('sliders');
    }


    public function show($id)
    {
        //
    }


    public function edit(Slider $slider)
    {
        return view('admin/slider/edit', compact('slider'));
    }


    public function update(SliderRequest $request, $id)
    {
        SliderServices::update($request, $id);
        Session::flash('flash_message', 'Data Berhasil di Simpan');
        return redirect('sliders');
    }

    public function destroy(Request $request, $id)
    {
        SliderServices::delete($request);
        Session::flash('flash_message', 'Data Berhasil di Hapus');
        return redirect('sliders');
    }
}

resources/views/admin/slider/create.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h5>Package Form</h5><hr>
        </div>

        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open(['route' => 'sliders.store', 'files' => true]) !!}
                            @include('admin/slider/form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/vendors/ckeditor_full/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace( 'content' );

        $("#image-input").change(function() {
            readURL(this);
        })

        function readURL(input) {
            if(input.files && input.files[0]) {
                var reader = new FileReader()

                reader.onload = function(e) {
                    $("#preview-image").attr("src", e.target.result)
                }

                reader.readAsDataURL(input.files[0]) // Convert to base 64 string
            }

        }
    </script>
@endsection

resources/views/admin/slider/edit.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h5>slider Form Edit</h5><hr>
        </div>

        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {!! Form::model($slider, ['method' => 'patch', 'route' => ['sliders.update', $slider->id], 'files' => true]) !!}
                            @include('admin/slider/form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/vendors/ckeditor_full/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace( 'content' );

        $("#image-input").change(function() {
            readURL(this);
        })

        function readURL(input) {
            if(input.files && input.files[0]) {
                var reader = new FileReader()

                reader.onload = function(e) {
                    $("#preview-image").attr("src", e.target.result)
                }

                reader.readAsDataURL(input.files[0]) // Convert to base 64 string
            }

        }
    </script>
@endsection

resources/views/admin/slider/form.blade.php
<div>
    <div class="text-center">
        <img src="{{ asset(!empty(($slider->image)) ? 'image/sliders/'.$slider->image : 'image/blank.png') }}" class="img-fluid" id="preview-image">
        <div class="form-group py-3">
            <input name="image" id="image-input" type="file" accept='image/*'>
            @error('image')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group">
        <h6 class="card-title">Title</h6>
        @php if($errors->has('title')) { $errorTitle = 'is-invalid'; } else {$errorTitle = ''; } @endphp
        {!! Form::text('title', null, ["class" => "form-control $errorTitle"]) !!}
        @error('title')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
    <div class="form-group">
        <h6 class="card-title">Order</h6>
        @php if($errors->has('order')) { $errorOrder = 'is-invalid'; } else {$errorOrder = ''; } @endphp
        {!! Form::number('order', null, ["class" => "form-control $errorOrder"]) !!}
        @error('order')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary btn-block">Submit</button>
</div>

resources/views/admin/slider/index.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h5>sliders</h5><hr>
            @include('partials/flash_message')
        </div>
        
        <div class="col-md-12">
            <div class="row row-cols-1 row-cols-md-2">
                <div class="col-lg-4 col-md-6 mb-3">
                    <a href="{{ route('sliders.create') }}">
                        <div class="card text-center py-4" style="height:100%">
                            <div class="card-body">
                                <span class="mdi mdi-plus mdi-48px"></span>
                                <h6>Tambah slider</h6>
                                <h5 class="card-title"></h5>
                            </div>
                        </div>
                    </a>
                </div>
                @foreach($data_slider as $slider)
                <div class="col-lg-4 mb-3">
                    <a href="{{ route('sliders.edit', [$slider->id]) }}">
                        <div class="card">
                            <div class="postion-relative">
                                <img src="{{ asset('image/sliders/'.$slider->image) }}" class="card-img-top" alt="...">
                                <div class="position-absolute" style="right:10px; top:10px;"><span class="badge badge-pill badge-primary">{{ $slider->order }}</span></div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">{{ $slider->title }}</h5>
                                <div class="float-right">
                                    <a  data-toggle="modal" data-target="#ModalDelete" data-id="{{ $slider->id }}" id="hapusData"><button class="btn btn-danger btn-sm">Hapus</button></a>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    @include('partials/modalDelete', ['route' => 'sliders.destroy'])
@endsection
@section('script')
@endsection