routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController')->name('home');
Route::post('/sendMail', 'EmailController@sendEmail')->name('sendMail');

Auth::routes(['register' => false]);

Route::get('/dashboard', function() {
    return view('admin/index');
})->name('dashboard')->middleware('auth');

Route::namespace('Admin')->group(function () {
    Route::resource('packages', 'PackageController');
    Route::resource('sliders', 'SliderController');
    Route::resource('web_setting', 'WebSettingController')->only([
        'index', 'store'
    ]);
    Route::resource('forms', 'FormsController')->only([
        'index', 'store', 'show', 'destroy'
    ]);
});
Route::get('/pendaftaran_alert', function() {
    return view('partials/formAlert');
});

Route::get('/contact_alert', function() {
    return view('partials/contactAlert');
});

app/Models/Package.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Package extends Model
{
    protected $table = 'packages';

    protected $fillable = [
        'image', 'title', 'package_name', 'slug', 'content', 'active'
    ];
    
    protected $primaryKey = 'slug';

    public $incrementing = false;

    public function forms()
    {
        return $this->hasMany('App\Models\Form', 'package_id');
    }

}

app/Http/Controllers/Admin/PackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Models\Package;
use App\Models\Provinsi;
use App\Models\KabKota;
use App\Services\Package\PackageServices;
use App\Http\Requests\Admin\PackageRequest;
use Session;

class PackageController extends Controller
{
    public function __construct() {
        $this->middleware('auth', ['except' => 
            ['show']
        ]);
    }

    public function index()
    {
        $data_package = PackageServices::getAll();
        return view('admin/package/index', compact('data_package'));
    }

    public function create()
    {
        return view('admin/package/create');
    }

    public function store(PackageRequest $request)
    {
        PackageServices::create($request);
        Session::flash('flash_message', 'Data Package Berhasil di Tambahkan');
        return redirect('packages');
        
    }

    public function show(Package $package)
    {
        return view('admin/package/show', compact('package'));
    }

    public function edit($slug)
    {

        $package = PackageServices::get_by_slug($slug);
        return view('admin/package/edit', compact('package'));
    }

    public function update(PackageRequest $request, $slug)
    {
        PackageServices::update($request, $slug);
        Session::flash('flash_message', 'Data Package Berhasil di Simpan');
        return redirect('packages');
    }

    public function destroy(Request $request, $id)
    {
        $id = $request->input('id');
        PackageServices::destroy($id);
        Session::flash('flash_message', 'Data Package Berhasil di Hapus');
        return redirect('packages');
    }
}

resources/views/admin/package/create.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h5>Package Form</h5><hr>
        </div>

        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open(['route' => 'packages.store', 'files' => true]) !!}
                            @include('admin/package/form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/vendors/ckeditor_full/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace( 'content' );

        $("#image-input").change(function() {
            readURL(this);
        })

        function readURL(input) {
            if(input.files && input.files[0]) {
                var reader = new FileReader()

                reader.onload = function(e) {
                    $("#preview-image").attr("src", e.target.result)
                }

                reader.readAsDataURL(input.files[0]) // Convert to base 64 string
            }

        }
    </script>
@endsection

resources/views/admin/package/edit.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h5>Package Form Edit</h5><hr>
        </div>

        <div class="col-lg-12 d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {!! Form::model($package, ['method' => 'patch', 'route' => ['packages.update', $package->slug], 'files' => true]) !!}
                            @include('admin/package/form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/vendors/ckeditor_full/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace( 'content' );

        $("#image-input").change(function() {
            readURL(this);
        })

        function readURL(input) {
            if(input.files && input.files[0]) {
                var reader = new FileReader()

                reader.onload = function(e) {
                    $("#preview-image").attr("src", e.target.result)
                }

                reader.readAsDataURL(input.files[0]) // Convert to base 64 string
            }

        }
    </script>
@endsection

resources/views/admin/package/form.blade.php
<div>
    <div class="text-center">
        <img src="{{ asset(!empty(($package->image)) ? 'image/packages/'.$package->image : 'image/blank.png') }}" class="img-fluid" id="preview-image">
        <div class="form-group py-3">
            <input name="image" id="image-input" type="file" accept='image/*'>
            @error('image')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <div class="form-group">
        <h6 class="card-title">Title</h6>
        @php if($errors->has('title')) { $errorTitle = 'is-invalid'; } else {$errorTitle = ''; } @endphp
        {!! Form::text('title', null, ["class" => "form-control $errorTitle"]) !!}
        @error('title')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>

    <div class="form-group">
        <h6 class="card-title">Package Name</h6>
        @php if($errors->has('package_name')) { $errorPackageName = 'is-invalid'; } else {$errorPackageName = ''; } @endphp
        {!! Form::text('package_name', null, ["class" => "form-control $errorPackageName"]) !!}
        @error('package_name')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>

    <div class="form-group">
        <h6 class="card-title">Content</h6>
        {!! Form::textarea('content', null) !!}
        @error('content')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>

    <div class="form-group">
        <h6 class="card-title">Active</h6>
        @php if($errors->has('active')) { $errorActive = 'is-invalid'; } else {$errorActive = ''; } @endphp
        {!! Form::select('active', ['true' => 'Active', 'false' => 'Not Active'], '', ['class' => 'form-control $errorActive']) !!}
        @error('active')
            <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary btn-block">Submit</button>
</div>

resources/views/admin/package/index.blade.php
@extends('dashboardTemplate')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h5>Packages</h5><hr>
            @include('partials/flash_message')
        </div>
        
        <div class="col-md-12">
            <div class="row row-cols-1 row-cols-md-2">
                <div class="col-lg-4 col-md-6 mb-3">
                    <a href="{{ route('packages.create') }}">
                        <div class="card text-center py-4" style="height:100%">
                            <div class="card-body">
                                <span class="mdi mdi-plus mdi-48px"></span>
                                <h6>Tambah Package</h6>
                                <h5 class="card-title"></h5>
                            </div>
                        </div>
                    </a>
                </div>
                @foreach($data_package as $package)
                <div class="col-lg-4 mb-3">
                    <a href="{{ route('packages.edit', [$package->slug]) }}">
                        <div class="card">
                            <div class="position-relative">
                                <img src="{{ asset('image/packages/'.$package->image) }}" class="card-img-top" alt="...">
                                @if($package->active == 'true')
                                    <div class="position-absolute" style="right:10px; top:10px;"><span class="badge badge-pill badge-primary">Active</span></div>
                                @else
                                    <div class="position-absolute" style="right:10px; top:10px;"><span class="badge badge-pill badge-danger">Not Active</span></div>
                                @endif
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">{{ $package->title }}</h5>
                                <div class="float-right">
                                    <a  data-toggle="modal" data-target="#ModalDelete" data-id="{{ $package->id }}" id="hapusData"><button class="btn btn-danger btn-sm">Hapus</button></a>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    @include('partials/modalDelete', ['route' => 'packages.destroy'])
@endsection

resources/views/admin/package/show.blade.php
@extends('layouts/frondendTemplate')
@section('content')
    <section id="content" class="clearfix mt-5 pt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 text-left">
                    <h2 class="font-weight-bold m-0" id="title">{{ $package->title }}</h2>
                    <small class="date">Super Indihome | <font id="date">{{ $package->updated_at }}</font></small>
                    
                    <div id="image">
                        <img src="{{ asset('image/packages/'.$package->image) }}" class="img-fluid">
                    </div>
                    
                    <div id="description" class="mt-5">
                    {!! $package->content !!}
                    </div>
                    
                </div>
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            {!! Form::open(['route' => 'forms.store']) !!}
                                <h3>Formulir Pendaftaran</h3>
                                <div class="form-group">
                                    <label class="font-weight-bold">PAKET YANG ANDA PILIH</label>
                                    <input type="text" name="package_name" value="{{ $package->title }}" class="form-control">
                                    <input type="hidden" name="package_id" class="form-control" value="{{ $package->id }}">
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">NAMA</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror">
                                    @error('nama')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">EMAIL</label>
                                    <input type="text" name="email" class="form-control @error('email') is-invalid @enderror">
                                    @error('email')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">NO. HANDPHONE</label>
                                    <input type="text" name="no_hp" class="form-control @error('no_hp') is-invalid @enderror">
                                    @error('no_hp')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                    <p style="font-size:12px;">
                                        Pastikan nomor Anda aktif agar dapat memudahkan petugas kami menghubungi Anda.
                                    </p>
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">PROVINSI</label>
                                    <select name="provinsi_id" id="provinsi" class="form-control @error('provinsi_id') is-invalid @enderror">
                                        <option value="">-- Pilih Provinsi --</option>
                                    </select>
                                    @error('provinsi_id')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">Kota</label>
                                    <select name="kab_kota_id" id="kab_kota" class="form-control @error('kab_kota_id') is-invalid @enderror">
                                        <option value="">-- Pilih Kota --</option>
                                    </select>
                                    @error('kab_kota_id')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
    
                                <div class="form-group">
                                    <label class="font-weight-bold">ALAMAT PEMASANG</label>
                                    <textarea name="alamat_pemasangan" rows="5" class="form-control @error('alamat_pemasangan') is-invalid @enderror"></textarea>
                                    @error('alamat_pemasangan')
                                        <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
    
                                <button class="btn btn-danger btn-block">Daftar</button>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $("#provinsi option:first").prop('disabled',true);
            $("#kab_kota option:first").prop('disabled',true);
            $("#kab_kota").prop("disabled", true);

            $.ajax({
                url: "http://superindihome.com/api/get_provinsi",
                type: "GET",
                dataType: "JSON",
                success: function(result) {
                    let data = result.data

                    $.each(data, function(key, value) {
                        let append = "<option value="+ value.id +">"+value.provinsi+"</option>"
                        $("#provinsi").append(append)
                    })
                }
            })

            $("#provinsi").change(function() {
                let provinsiVal = $("#provinsi").val();
                $.ajax({
                    url: "http://superindihome.com/api/get_kab_kota/"+provinsiVal,
                    type: "GET",
                    dataType: "JSON",
                    success: function(result) {
                        let data = result.data
                        $("#kab_kota").prop("disabled", false)
                        $("#kab_kota").html("")
                        $.each(data, function(key, value) {
                            let append = "<option value="+ value.id +">"+value.kab_kota+"</option>"
                            $("#kab_kota").append(append)
                        })
                    }
                })
            })
        })
    </script>
@endsection